Starting to see results ...

diff --git a/templates/media-usb.sh.j2 b/templates/media-usb.sh.j2
--- a/templates/media-usb.sh.j2
+++ b/templates/media-usb.sh.j2
@@ -1,5 +1,22 @@
 #!/bin/sh
 
+OPT="-p"
+
+OPTSTRING=":f"
+
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    f)
+      OPT="" 
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+
+
 DEVICE="{{ cc.dev }}"
 CIDATADIR="{{ cc.cidatadir }}"
 URL="{{ cc.url }}"
@@ -14,13 +31,13 @@ cd $DIR &&   shasum -a 256 -c $CIDATADIR/signatures | grep "^$ISO: OK" || { curl
 
 # We check if device is removable
 test  "$(lsblk -l -p -n $DEVICE -o HOTPLUG | sort |uniq)" -eq "1" && {
-lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r -p sudo umount
+lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r $OPT sudo umount
 #sudo dd if=/dev/zero of=$DEVICE bs=512 count=1 seek=0
 sudo sfdisk --delete $DEVICE
 sudo usb-creator-gtk --iso=$FILE
 
 #sudo dd if=$FILE of=$DEVICE bs=1k conv=fdatasync status=progress
 sudo partprobe $DEVICE
-lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r -p sudo umount
+lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r $OPT sudo umount
 }
 
diff --git a/templates/nocloud-usb.sh.j2 b/templates/nocloud-usb.sh.j2
--- a/templates/nocloud-usb.sh.j2
+++ b/templates/nocloud-usb.sh.j2
@@ -1,11 +1,28 @@
 #!/bin/sh
 
+
+OPT="-p"
+
+OPTSTRING=":f"
+
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    f)
+      OPT=""
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+
 DEVICE="{{ cc.dev }}"
 CIDATADIR="{{ cc.cidatadir }}"
 
 
 test  "$(lsblk -l -p -n $DEVICE -o HOTPLUG | sort |uniq)" -eq "1" && {
 cd $CIDATADIR && cloud-localds nocloud.iso   user-data meta-data
-lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r -p sudo umount
+lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r $OPT sudo umount
 sudo dd if=nocloud.iso of=$DEVICE bs=1k conv=fdatasync status=progress
 }
