step

diff --git a/templates/media-usb.sh.j2 b/templates/media-usb.sh.j2
--- a/templates/media-usb.sh.j2
+++ b/templates/media-usb.sh.j2
@@ -17,7 +17,7 @@ while getopts ${OPTSTRING} opt; do
 done
 
 
-DEVICE="{{ cc.dev }}"
+DEVICE="{{ cc.deviso | default(cc.dev) }}"
 CIDATADIR="{{ cc.cidatadir }}"
 URL="{{ cc.url }}"
 DIR="{{ cc.dir }}"
@@ -25,12 +25,17 @@ DIR="{{ cc.dir }}"
 ISO="${URL##*/}"
 FILE=$DIR/$ISO
 
-# We download the iso
-cd $DIR &&   shasum -a 256 -c $CIDATADIR/signatures | grep "^$ISO: OK" || { curl $URL | tee $FILE | sha256sum ; }
+echo "We download  $ISO if the file with  the signature is not found"
+cd $DIR &&   shasum -a 256 -c $CIDATADIR/signatures 2>&1 | grep "^$ISO: OK" || { curl $URL | tee $FILE | sha256sum ; }
 
 
-# We check if device is removable
-test  "$(lsblk -l -p -n $DEVICE -o HOTPLUG | sort |uniq)" -eq "1" && {
+
+echo "We check if device $DEVICE is removable"
+
+FDEVICE="$(lsblk -l -p -n $DEVICE -o HOTPLUG | sort |uniq)"
+
+
+test -n "$FDEVICE" && test  "$FDEVICE" -eq "1" && {
 lsblk -l -p -n $DEVICE  | awk 'NF > 6 {print $1}' | xargs -n1 -r $OPT sudo umount
 #sudo dd if=/dev/zero of=$DEVICE bs=512 count=1 seek=0
 sudo sfdisk --delete $DEVICE
